name: bw2kp

services:
  bitwarden-to-keepass:
    image: ghcr.io/lanjelin/bw2kp
    container_name: bitwarden-to-keepass
    volumes:
      - ./exports:/exports
      - ./bw-config:/root/.config
    env_file:
      - .env
